# Generated by Django 4.0.4 on 2022-08-17 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abd_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='abd_database.hdf5file'),
        ),
        migrations.AddField(
            model_name='hdf5file',
            name='file_name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='celltest',
            name='equipment',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='cyclingtest',
            name='cellTest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_test_type', to='abd_database.celltest'),
        ),
        migrations.AlterField(
            model_name='eistest',
            name='cellTest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_test_type', to='abd_database.celltest'),
        ),
    ]
