# Generated by Django 4.0.4 on 2023-04-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abd_database', '0006_alter_uploadbatch_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='battery',
            name='prod_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='comments',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
