# Generated by Django 4.0.4 on 2023-08-18 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abd_database', '0010_auto_20230815_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='battery_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='batteries', to='abd_database.batterytype'),
        ),
    ]
