# Generated by Django 4.0.4 on 2023-12-11 11:30

from django.db import migrations

# Reverts the 0010 migration which was used for access control via guardian
def revert_create_dataset_groups(apps, schema_editor):
    Dataset = apps.get_model('abd_database', 'Dataset')
    Group = apps.get_model('auth', 'Group')
    for dataset in Dataset.objects.exclude(pk=1):
        group = Group.objects.get(name=f'dataset_{dataset.pk}')
        group.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('abd_database', '0014_battery_owner'),
    ]

    operations = [
    ]
