# Generated by Django 3.2.8 on 2022-05-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abd_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_upload', 'Can upload HDF5-Files')]},
        ),
    ]
