# Generated by Django 4.0.4 on 2023-08-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abd_management', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_upload', 'Can upload test-files')]},
        ),
    ]
